services:
  web:
    build: .
    image: niggiover9000/donation:latest
    container_name: donation_app
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ADMIN_PASSWORD="admin"
    volumes:
      - ./donation.db:/app/donation.db
      - ./sounds/:/app/sounds/
